apiVersion: argocd.akuity.io/v1alpha1
kind: ArgoCD
metadata:
  name: my-argocd-instance
spec:
  description: "Argo CD Instance for Kargo Quickstart"
  instanceSpec:
    assistantExtensionEnabled: true   # enable Akuity Intelligence (AI assistant)
  version: v3.4.3-ak.92